apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "authgear.namePortal" . | quote }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "authgear.namePortal" . | quote }}
  namespace: {{ .Values.mainServer.env.CONFIG_SOURCE_KUBE_NAMESPACE | quote }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "authgear.namePortal" . | quote }}
  namespace: {{ .Values.mainServer.env.CONFIG_SOURCE_KUBE_NAMESPACE | quote }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "authgear.namePortal" . | quote }}
  namespace: {{ .Values.namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "authgear.namePortal" . | quote }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authgear.namePortal" . | quote }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "authgear.portalSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authgear.portalSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "authgear.namePortal" . | quote }}
      volumes:
      - name: volume-ingress-template
        configMap:
          name: {{ .Values.portalServer.configMap.ingressTemplate.name | quote }}
          items:
          - key: ingress.tpl.yaml
            path: ingress.tpl.yaml
      containers:
      - name: authgear-portal-server
        image: {{ .Values.portalServer.image | quote }}
        volumeMounts:
        - name: volume-ingress-template
          mountPath: /app/configmap/ingress-template
        env:
        - name: DATABASE_URL
          value: {{ .Values.portalServer.env.DATABASE_URL | quote }}
        - name: TRUST_PROXY
          value: {{ .Values.portalServer.env.TRUST_PROXY | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.portalServer.env.LOG_LEVEL | quote }}
        - name: SENTRY_DSN
          value: {{ .Values.portalServer.env.SENTRY_DSN | quote }}
        - name: CONFIG_SOURCE_TYPE
          value: {{ .Values.portalServer.env.CONFIG_SOURCE_TYPE | quote }}
        - name: CONFIG_SOURCE_KUBE_NAMESPACE
          value: {{ .Values.portalServer.env.CONFIG_SOURCE_KUBE_NAMESPACE | quote }}
        - name: AUTHGEAR_CLIENT_ID
          value: {{ .Values.portalServer.env.AUTHGEAR_CLIENT_ID | quote }}
        - name: AUTHGEAR_ENDPOINT
          value: {{ .Values.portalServer.env.AUTHGEAR_ENDPOINT | quote }}
        - name: ADMIN_API_TYPE
          value: {{ .Values.portalServer.env.ADMIN_API_TYPE | quote }}
        - name: ADMIN_API_AUTH
          value: {{ .Values.portalServer.env.ADMIN_API_AUTH | quote }}
        - name: ADMIN_API_ENDPOINT
          value: {{ .Values.portalServer.env.ADMIN_API_ENDPOINT | quote }}
        - name: ADMIN_API_HOST_TEMPLATE
          value: {{ .Values.portalServer.env.ADMIN_API_HOST_TEMPLATE | quote }}
        - name: APP_HOST_TEMPLATE
          value: {{ .Values.portalServer.env.APP_HOST_TEMPLATE | quote }}
        - name: APP_SECRET_DATABASE_URL
          value: {{ .Values.portalServer.env.APP_SECRET_DATABASE_URL | quote }}
        - name: APP_SECRET_DATABASE_SCHEMA
          value: {{ .Values.portalServer.env.APP_SECRET_DATABASE_SCHEMA | quote }}
        - name: APP_SECRET_REDIS_URL
          value: {{ .Values.portalServer.env.APP_SECRET_REDIS_URL | quote }}
        - name: APP_SECRET_SMTP_HOST
          value: {{ .Values.portalServer.env.APP_SECRET_SMTP_HOST | quote }}
        - name: APP_SECRET_SMTP_PORT
          value: {{ .Values.portalServer.env.APP_SECRET_SMTP_PORT | quote }}
        - name: APP_SECRET_SMTP_MODE
          value: {{ .Values.portalServer.env.APP_SECRET_SMTP_MODE | quote }}
        - name: APP_SECRET_SMTP_USERNAME
          value: {{ .Values.portalServer.env.APP_SECRET_SMTP_USERNAME | quote }}
        - name: APP_SECRET_SMTP_PASSWORD
          value: {{ .Values.portalServer.env.APP_SECRET_SMTP_PASSWORD | quote }}
        - name: APP_SECRET_TWILIO_ACCOUNT_SID
          value: {{ .Values.portalServer.env.APP_SECRET_TWILIO_ACCOUNT_SID | quote }}
        - name: APP_SECRET_TWILIO_AUTH_TOKEN
          value: {{ .Values.portalServer.env.APP_SECRET_TWILIO_AUTH_TOKEN | quote }}
        - name: APP_KUBERNETES_INGRESS_TEMPLATE_FILE
          value: /app/configmap/ingress-template/ingress.tpl.yaml
        - name: APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_TYPE
          value: {{ .Values.portalServer.env.APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_TYPE | quote }}
        - name: APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_SECRET_NAME
          value: {{ .Values.portalServer.env.APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_SECRET_NAME | quote }}
        - name: APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_ISSUER_KIND
          value: {{ .Values.portalServer.env.APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_ISSUER_KIND | quote }}
        - name: APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_ISSUER_NAME
          value: {{ .Values.portalServer.env.APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_ISSUER_NAME | quote }}
        - name: APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_TYPE
          value: {{ .Values.portalServer.env.APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_TYPE | quote }}
        - name: APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_SECRET_NAME
          value: {{ .Values.portalServer.env.APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_SECRET_NAME | quote }}
        - name: APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_ISSUER_KIND
          value: {{ .Values.portalServer.env.APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_ISSUER_KIND | quote }}
        - name: APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_ISSUER_NAME
          value: {{ .Values.portalServer.env.APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_ISSUER_NAME | quote }}
        - name: APP_BRANDING_APP_NAME
          value: {{ .Values.portalServer.env.APP_BRANDING_APP_NAME | quote }}
        - name: APP_BRANDING_EMAIL_DEFAULT_SENDER
          value: {{ .Values.portalServer.env.APP_BRANDING_EMAIL_DEFAULT_SENDER | quote }}
        - name: APP_BRANDING_SMS_DEFAULT_SENDER
          value: {{ .Values.portalServer.env.APP_BRANDING_SMS_DEFAULT_SENDER | quote }}
        ports:
        - name: http
          containerPort: 3003
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          {{- toYaml .Values.portalServer.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authgear.namePortal" . | quote }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "authgear.portalSelectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "authgear.namePortal" . | quote }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://{{- include "authgear.nameResolver" . -}}.{{ .Values.namespace }}.svc.cluster.local/resolve"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-authgear-session-valid, x-authgear-user-id, x-authgear-user-anonymous, x-authgear-user-verified, x-authgear-session-acr, x-authgear-session-amr"
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host {{ .Values.portalServer.authgearHost }};
spec:
  tls:
  - secretName: {{ .Values.portalServer.ingress.tls.secretName | quote }}
    hosts:
    - {{ .Values.portalServer.ingress.host | quote }}
  rules:
  - host: {{ .Values.portalServer.ingress.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "authgear.namePortal" . | quote }}
          servicePort: http
