apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authgear.nameResolver" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "authgear.resolverSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authgear.resolverSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "authgear.nameMain" . | quote }}
      {{ if .Values.authgear.appCustomResources.path }}
      volumes:
      - name: custom-resources
        {{- toYaml .Values.authgear.appCustomResources.volume | nindent 8 }}
      {{ end }}
      containers:
      - name: authgear-resolver-server
        image: {{ .Values.authgear.mainServer.image | quote }}
        args: ["authgear", "start", "resolver"]
        {{ if .Values.authgear.appCustomResources.path }}
        volumeMounts:
        - name: custom-resources
          mountPath: {{ .Values.authgear.appCustomResources.path | quote }}
        {{ end }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.authgear.databaseURL | quote }}
        - name: DATABASE_SCHEMA
          value: {{ .Values.authgear.databaseSchema | quote }}
        - name: TRUST_PROXY
          value: {{ .Values.authgear.trustProxy | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.authgear.logLevel | quote }}
        - name: SENTRY_DSN
          value: {{ .Values.authgear.sentryDSN | quote }}
        - name: CONFIG_SOURCE_TYPE
          value: {{ .Values.authgear.configSourceType | quote }}
        - name: CONFIG_SOURCE_KUBE_NAMESPACE
          value: {{ .Values.authgear.appNamespace | quote }}
        - name: CUSTOM_RESOURCE_DIRECTORY
          value: {{ .Values.authgear.appCustomResources.path | quote }}
        {{- range $key, $val := .Values.authgear.mainServer.env }}
        - name: {{ $key | quote }}
          value: {{ $val | quote }}
        {{- end }}
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          {{- toYaml .Values.authgear.resolverServer.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authgear.nameResolver" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "authgear.resolverSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authgear.nameResolver" . | quote }}
  namespace: {{ .Values.authgear.appNamespace | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ include "authgear.nameResolver" . }}.{{ .Release.Namespace }}.svc.cluster.local
  ports:
  - port: 80
