{{ if .Values.authgear.auditLog.cronjob.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "authgear.nameAuditLogCron" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.authgear.auditLog.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: authgear-audit-log-cronjob
            image: {{ .Values.authgear.mainServer.image | quote }}
            args: ["authgear", "audit", "database", "maintain"]
            env:
            - name: DATABASE_URL
              value: {{ .Values.authgear.auditLog.databaseURL | quote }}
            - name: DATABASE_SCHEMA
              value: {{ .Values.authgear.auditLog.databaseSchema | quote }}
          restartPolicy: Never
{{ end }}
