{{ if not .Values.skipCRDResources }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirecthttptohttps
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirecthttptohttps
  namespace: {{ .Values.authgear.appNamespace | quote }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: correcthostforforwardauth
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Host: {{ .Values.authgear.portalServer.authgearHost | quote }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forwardauth
spec:
  forwardAuth:
    address: http://{{ include "authgear.nameResolver" . }}.{{ .Release.Namespace }}.svc.cluster.local/resolve
    trustForwardHeader: true
    authResponseHeaders:
    - x-authgear-session-valid
    - x-authgear-user-id
    - x-authgear-user-anonymous
    - x-authgear-user-verified
    - x-authgear-session-acr
    - x-authgear-session-amr
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: reverthostforupstream
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Host: {{ .Values.authgear.portalServer.ingress.host | quote }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefixadmin
  namespace: {{ .Values.authgear.appNamespace | quote }}
spec:
  stripPrefix:
    prefixes:
      - /_api/admin
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefixresolver
  namespace: {{ .Values.authgear.appNamespace | quote }}
spec:
  stripPrefix:
    prefixes:
      - /_resolver
{{ end }}
