apiVersion: v2
type: application
name: authgear
description: A Helm chart for Authgear
version: 0.15.0
appVersion: 0.1.0
dependencies:
- name: traefik
  version: 9.8.3
  repository: "https://helm.traefik.io/traefik"
  condition: subcharts.traefik.enabled
- name: redis
  version: 11.0.3
  repository: "https://charts.bitnami.com/bitnami"
  condition: subcharts.redis.enabled
