authgear:
  appNamespace: "authgear-apps"

  databaseURL: postgres://localhost
  configSourceType: "database"
  trustProxy: "true"
  logLevel: "info"
  sentryDSN: ""

  auditLog:
    cronjob:
      enabled: false
      schedule: "0 0 * * *"
    databaseURL: postgres://localhost
    databaseSchema: public

  analytic:
    cronjob:
      enabled: false
      weeklySchedule: "0 1 * * 1"
    databaseURL: postgres://localhost
    databaseSchema: public
    auditDatabaseURL: postgres://localhost
    auditDatabaseSchema: public
    analyticRedisURL: __replace_me__
    googleSpreadsheetID: __replace_me__
    googleSpreadsheetRange:
      userWeeklyReport: __replace_me__
      projectWeeklyReport: __replace_me__
    googleSheetsSecret:
      path: ""
      volume: {}

  mainServer:
    image: __replace_me__

    env:
      ADMIN_API_AUTH: "jwt"

    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi

  adminServer:
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 300m
        memory: 64Mi

  resolverServer:
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 300m
        memory: 64Mi

  portalServerProxy:
    image: nginx:1.18

  portalServer:
    image: __replace_me__

    ingress:
      host: __replace_me__.example.com

    authgearHost: __replace_me__.example.com
    appHostWildcard: "*.example.com"

    configMap:
      ingressTemplate:
        name: __replace_me__

    env:
      SMTP_HOST: __replace_me__
      SMTP_PORT: 587
      SMTP_MODE: normal
      SMTP_USERNAME: __replace_me__
      SMTP_PASSWORD: __replace_me__
      MAIL_SENDER: __replace_me__
      MAIL_REPLY_TO: __replace_me__
      AUTHGEAR_APP_ID: __replace_me__
      AUTHGEAR_CLIENT_ID: __replace_me__
      AUTHGEAR_ENDPOINT: https://__replace_me__.example.com
      ADMIN_API_TYPE: "static"
      ADMIN_API_AUTH: "jwt"
      ADMIN_API_ENDPOINT: __replace_me__.example.com
      ADMIN_API_HOST_TEMPLATE: "{{ .AppID }}.example.com"
      APP_HOST_SUFFIX: ".example.com"
      APP_MAX_OWNED_APPS: "-1"
      APP_SECRET_KEY_ALLOWLIST: admin-api.auth,sso.oauth.client,webhook

  appCustomResources:
    path: ""
    volume: {}

  portalCustomResources:
    path: ""
    volume: {}
