authgear:
  appNamespace: "authgear-apps"

  databaseURL: postgres://localhost
  databaseSchema: public

  redisURL: redis://localhost

  configSourceType: "database"
  trustProxy: "true"
  logLevel: "info"
  sentryDSN: ""

  ingress:
    class: nginx

  certManager:
    enabled: true
    issuer:
      dns01:
        name: __replace_me__
      http01:
        name: __replace_me__

  tls:
    wildcard:
      secretName: ""
    portal:
      secretname: ""
    portalAuthgear:
      secretName: ""

  baseHost: __replace_me__

  smtp:
    host: __replace_me__
    port: 587
    mode: normal
    username: ""
    password: ""

  elasticsearch:
    enabled: false
    url: http://localhost:9200

  twilio:
    accountSID: ""
    authToken: ""

  auditLog:
    enabled: false
    cronjob:
      enabled: false
      schedule: "0 0 * * *"
    databaseURL: postgres://localhost
    databaseSchema: public

  analytic:
    cronjob:
      enabled: false
      weeklySchedule: "0 1 * * 1"
      monthlySchedule: "10 1 1 * *"
      dailySchedule: "20 1 * * *"
    analyticRedisURL: __replace_me__
    googleSpreadsheetID: __replace_me__
    googleSpreadsheetRange:
      userWeeklyReport: __replace_me__
      projectWeeklyReport: __replace_me__
      projectMonthlyReport: __replace_me__
    googleSheetsSecret:
      path: ""
      volume: {}

  mainServer:
    image: __replace_me__
    env: {}
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi

  adminServer:
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 500m
        memory: 256Mi

  resolverServer:
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 500m
        memory: 256Mi

  background:
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 300m
        memory: 64Mi

  portalServerProxy:
    image: nginx:1.18

  portalServer:
    image: __replace_me__

    email:
      sender: ""
      replyTo: ""

    authgear:
      appID: __replace_me__
      clientID: __replace_me__
      endpoint: https://__replace_me__.example.com

    adminAPI:
      endpoint: http://cluster.local

    customDomain:
      enabled: true

    env: {}

    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi

  appCustomResources:
    path: ""
    volume: {}

  portalCustomResources:
    path: ""
    volume: {}
